=== juandesi/raml-to-retrofit/src/test/resources/twitter/schemas/followers-ids-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "connections": {
        "required": false,
        "type": "array",
        "items": {
          "required": false,
          "type": "string"
        }
      },
      "id": {
        "required": false,
        "type": "integer"
      },
      "id_str": {
        "required": false,
        "type": "string"
      },
      "name": {
        "required": false,
        "type": "string"
      },
      "screen_name": {
        "required": false,
        "type": "string"
      }
    }
  }
}

=== juandesi/raml-to-retrofit/src/test/resources/twitter/examples/followers-ids-example.json
[
    {
        "name": "Taylor Singletary",
        "id_str": "819797",
        "id": 819797,
        "connections": [
            "none"
        ],
        "screen_name": "episod"
    },
    {
        "name": "Twitter API",
        "id_str": "6253282",
        "id": 6253282,
        "connections": [
            "following",
            "followed_by"
        ],
        "screen_name": "twitterapi"
    }
]
