=== juandesi/raml-to-retrofit/src/test/resources/twitter/schemas/lists-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "created_at": {
        "required": false,
        "type": "string"
      },
      "description": {
        "required": false,
        "type": "string"
      },
      "following": {
        "required": false,
        "type": "boolean"
      },
      "full_name": {
        "required": false,
        "type": "string"
      },
      "id": {
        "required": false,
        "type": "integer"
      },
      "id_str": {
        "required": false,
        "type": "string"
      },
      "member_count": {
        "required": false,
        "type": "integer"
      },
      "mode": {
        "required": false,
        "type": "string"
      },
      "name": {
        "required": false,
        "type": "string"
      },
      "slug": {
        "required": false,
        "type": "string"
      },
      "subscriber_count": {
        "required": false,
        "type": "integer"
      },
      "uri": {
        "required": false,
        "type": "string"
      },
      "user": {
        "required": false,
        "type": "object",
        "properties": {
          "profile_background_tile": {
            "required": false,
            "type": "boolean"
          },
          "profile_sidebar_border_color": {
            "required": false,
            "type": "string"
          },
          "name": {
            "required": false,
            "type": "string"
          },
          "profile_sidebar_fill_color": {
            "required": false,
            "type": "string"
          },
          "location": {
            "required": false,
            "type": "string"
          },
          "created_at": {
            "required": false,
            "type": "string"
          },
          "profile_image_url": {
            "required": false,
            "type": "string"
          },
          "is_translator": {
            "required": false,
            "type": "boolean"
          },
          "id_str": {
            "required": false,
            "type": "string"
          },
          "profile_link_color": {
            "required": false,
            "type": "string"
          },
          "follow_request_sent": {
            "required": false,
            "type": "boolean"
          },
          "favourites_count": {
            "required": false,
            "type": "integer"
          },
          "contributors_enabled": {
            "required": false,
            "type": "boolean"
          },
          "url": {
            "required": false,
            "type": "string"
          },
          "default_profile": {
            "required": false,
            "type": "boolean"
          },
          "profile_image_url_https": {
            "required": false,
            "type": "string"
          },
          "utc_offset": {
            "required": false,
            "type": "integer"
          },
          "profile_banner_url": {
            "required": false,
            "type": "string"
          },
          "id": {
            "required": false,
            "type": "integer"
          },
          "profile_use_background_image": {
            "required": false,
            "type": "boolean"
          },
          "listed_count": {
            "required": false,
            "type": "integer"
          },
          "profile_text_color": {
            "required": false,
            "type": "string"
          },
          "protected": {
            "required": false,
            "type": "boolean"
          },
          "lang": {
            "required": false,
            "type": "string"
          },
          "followers_count": {
            "required": false,
            "type": "integer"
          },
          "description": {
            "required": false,
            "type": "string"
          },
          "notifications": {
            "required": false,
            "type": "boolean"
          },
          "geo_enabled": {
            "required": false,
            "type": "boolean"
          },
          "verified": {
            "required": false,
            "type": "boolean"
          },
          "time_zone": {
            "required": false,
            "type": "string"
          },
          "profile_background_color": {
            "required": false,
            "type": "string"
          },
          "profile_background_image_url_https": {
            "required": false,
            "type": "string"
          },
          "statuses_count": {
            "required": false,
            "type": "integer"
          },
          "friends_count": {
            "required": false,
            "type": "integer"
          },
          "default_profile_image": {
            "required": false,
            "type": "boolean"
          },
          "profile_background_image_url": {
            "required": false,
            "type": "string"
          },
          "following": {
            "required": false,
            "type": "boolean"
          },
          "screen_name": {
            "required": false,
            "type": "string"
          }
        }
      }
    }
  }
}

=== juandesi/raml-to-retrofit/src/test/resources/twitter/examples/lists-example.json
[
  {
    "slug": "meetup-20100301",
    "name": "meetup-20100301",
    "created_at": "Sat Feb 27 21:39:24 +0000 2010",
    "uri": "/twitterapi/meetup-20100301",
    "subscriber_count": 147,
    "id_str": "8044403",
    "member_count": 116,
    "mode": "public",
    "id": 8044403,
    "full_name": "@twitterapi/meetup-20100301",
    "description": "Guests attending the Twitter meetup on 1 March 2010 at the @twoffice",
    "user": {
      "profile_background_tile": true,
      "profile_sidebar_border_color": "C0DEED",
      "name": "Twitter API",
      "profile_sidebar_fill_color": "DDEEF6",
      "location": "San Francisco, CA",
      "created_at": "Wed May 23 06:01:13 +0000 2007",
      "profile_image_url": "http://a0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png",
      "is_translator": false,
      "id_str": "6253282",
      "profile_link_color": "0084B4",
      "follow_request_sent": false,
      "favourites_count": 25,
      "contributors_enabled": true,
      "url": "http://dev.twitter.com",
      "default_profile": false,
      "profile_image_url_https": "https://si0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png",
      "utc_offset": -28800,
      "profile_banner_url": "https://si0.twimg.com/profile_banners/6253282/1347394302",
      "id": 6253282,
      "profile_use_background_image": true,
      "listed_count": 11201,
      "profile_text_color": "333333",
      "protected": false,
      "lang": "en",
      "followers_count": 1444739,
      "description": "The Real Twitter API. I tweet about API changes, service issues and happily answer questions about Twitter and our API. Don't get an answer? It's on my website.",
      "notifications": false,
      "geo_enabled": true,
      "verified": true,
      "time_zone": "Pacific Time (US & Canada)",
      "profile_background_color": "C0DEED",
      "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png",
      "statuses_count": 3367,
      "friends_count": 33,
      "default_profile_image": false,
      "profile_background_image_url": "http://a0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png",
      "following": true,
      "screen_name": "twitterapi"
    },
    "following": false
  },
  {
    "slug": "team",
    "name": "team",
    "created_at": "Wed Nov 04 01:24:28 +0000 2009",
    "uri": "/twitterapi/team",
    "subscriber_count": 277,
    "id_str": "2031945",
    "member_count": 20,
    "mode": "public",
    "id": 2031945,
    "full_name": "@twitterapi/team",
    "description": "",
    "user": {
      "profile_background_tile": true,
      "profile_sidebar_border_color": "C0DEED",
      "name": "Twitter API",
      "profile_sidebar_fill_color": "DDEEF6",
      "location": "San Francisco, CA",
      "created_at": "Wed May 23 06:01:13 +0000 2007",
      "profile_image_url": "http://a0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png",
      "is_translator": false,
      "id_str": "6253282",
      "profile_link_color": "0084B4",
      "follow_request_sent": false,
      "favourites_count": 25,
      "contributors_enabled": true,
      "url": "http://dev.twitter.com",
      "default_profile": false,
      "profile_image_url_https": "https://si0.twimg.com/profile_images/2284174872/7df3h38zabcvjylnyfe3_normal.png",
      "utc_offset": -28800,
      "profile_banner_url": "https://si0.twimg.com/profile_banners/6253282/1347394302",
      "id": 6253282,
      "profile_use_background_image": true,
      "listed_count": 11201,
      "profile_text_color": "333333",
      "protected": false,
      "lang": "en",
      "followers_count": 1444739,
      "description": "The Real Twitter API. I tweet about API changes, service issues and happily answer questions about Twitter and our API. Don't get an answer? It's on my website.",
      "notifications": false,
      "geo_enabled": true,
      "verified": true,
      "time_zone": "Pacific Time (US & Canada)",
      "profile_background_color": "C0DEED",
      "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png",
      "statuses_count": 3367,
      "friends_count": 33,
      "default_profile_image": false,
      "profile_background_image_url": "http://a0.twimg.com/profile_background_images/656927849/miyt9dpjz77sc0w3d4vj.png",
      "following": true,
      "screen_name": "twitterapi"
    },
    "following": true
  }
]

=== juandesi/raml-to-retrofit/src/test/resources/twitter/examples/lists-destroy-example.json
{
    "created_at": "Fri Nov 04 21:22:36 +0000 2011",
    "slug": "goonies",
    "name": "Goonies",
    "full_name": "@kurrik/goonies",
    "description": "For life",
    "mode": "public",
    "following": false,
    "user": {
        "geo_enabled": true,
        "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/342542280/background7.png",
        "profile_background_color": "8fc1ff",
        "protected": false,
        "default_profile": false,
        "listed_count": 127,
        "profile_background_tile": true,
        "created_at": "Thu Jul 19 15:58:07 +0000 2007",
        "friends_count": 291,
        "name": "Arne Roomann-Kurrik",
        "profile_sidebar_fill_color": "c7e0ff",
        "notifications": false,
        "utc_offset": -28800,
        "profile_image_url_https": "https://si0.twimg.com/profile_images/24229162/arne001_normal.jpg",
        "description": "Developer Advocate at Twitter, practitioner of dark sandwich arts. ",
        "display_url": "roomanna.com",
        "following": false,
        "verified": false,
        "favourites_count": 190,
        "profile_sidebar_border_color": "6baeff",
        "followers_count": 1705,
        "profile_image_url": "http://a2.twimg.com/profile_images/24229162/arne001_normal.jpg",
        "default_profile_image": false,
        "contributors_enabled": false,
        "deactivated_bit": false,
        "statuses_count": 1935,
        "profile_use_background_image": true,
        "location": "Scan Francesco",
        "id_str": "7588892",
        "show_all_inline_media": false,
        "profile_text_color": "000000",
        "screen_name": "kurrik",
        "follow_request_sent": false,
        "profile_background_image_url": "http://a2.twimg.com/profile_background_images/342542280/background7.png",
        "url": "http://t.co/SSiVavc4",
        "expanded_url": "http://roomanna.com",
        "is_translator": false,
        "time_zone": "Pacific Time (US & Canada)",
        "profile_link_color": "0084B4",
        "id": 7588892,
        "entities": {
            "urls": [],
            "user_mentions": [],
            "hashtags": []
        },
        "suspended": false,
        "lang": "en"
    },
    "member_count": 0,
    "id_str": "58300198",
    "subscriber_count": 0,
    "id": 58300198,
    "uri": "/kurrik/goonies"
}
