=== juandesi/raml-to-retrofit/src/test/resources/twitter/schemas/saved_searches-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "created_at": {
        "required": false,
        "type": "string"
      },
      "id": {
        "required": false,
        "type": "integer"
      },
      "id_str": {
        "required": false,
        "type": "string"
      },
      "name": {
        "required": false,
        "type": "string"
      },
      "position": {
        "required": false,
        "type": "null"
      },
      "query": {
        "required": false,
        "type": "string"
      }
    }
  }
}

=== juandesi/raml-to-retrofit/src/test/resources/twitter/examples/saved_searches-example.json
[
  {
    "created_at": "Tue Jun 15 09:37:24 +0000 2010",
    "id": 9569704,
    "id_str": "9569704",
    "name": "@twitterapi",
    "position": null,
    "query": "@twitterapi"
  },
  {
    "created_at": "Tue Jun 15 09:38:04 +0000 2010",
    "id": 9569730,
    "id_str": "9569730",
    "name": "@twitter OR twitterapi OR \"twitter api\" OR \"@anywhere\"",
    "position": null,
    "query": "@twitter OR twitterapi OR \"twitter api\" OR \"@anywhere\""
  }
]
