=== juandesi/raml-to-retrofit/src/test/resources/twitter/schemas/trends-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "as_of": {
        "required": false,
        "type": "string"
      },
      "created_at": {
        "required": false,
        "type": "string"
      },
      "locations": {
        "required": false,
        "type": "array",
        "items": {
          "required": false,
          "type": "object",
          "properties": {
            "name": {
              "required": false,
              "type": "string"
            },
            "woeid": {
              "required": false,
              "type": "integer"
            }
          }
        }
      },
      "trends": {
        "required": false,
        "type": "array",
        "items": {
          "required": false,
          "type": "object",
          "properties": {
            "events": {
              "required": false,
              "type": "null"
            },
            "name": {
              "required": false,
              "type": "string"
            },
            "promoted_content": {
              "required": false,
              "type": "null"
            },
            "query": {
              "required": false,
              "type": "string"
            },
            "url": {
              "required": false,
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== juandesi/raml-to-retrofit/src/test/resources/twitter/examples/trends-example.json
[
  {
    "as_of": "2012-08-24T23:25:43Z", 
    "created_at": "2012-08-24T23:24:14Z", 
    "locations": [
      {
        "name": "Worldwide", 
        "woeid": 1
      }
    ], 
    "trends": [
      {
        "events": null, 
        "name": "#GanaPuntosSi", 
        "promoted_content": null, 
        "query": "%23GanaPuntosSi", 
        "url": "http://twitter.com/search/?q=%23GanaPuntosSi"
      }, 
      {
        "events": null, 
        "name": "#WordsThatDescribeMe", 
        "promoted_content": null, 
        "query": "%23WordsThatDescribeMe", 
        "url": "http://twitter.com/search/?q=%23WordsThatDescribeMe"
      }, 
      {
        "events": null, 
        "name": "#10PersonasQueExtra\u00f1oMucho", 
        "promoted_content": null, 
        "query": "%2310PersonasQueExtra%C3%B1oMucho", 
        "url": "http://twitter.com/search/?q=%2310PersonasQueExtra%C3%B1oMucho"
      }, 
      {
        "events": null, 
        "name": "Apple $1.5", 
        "promoted_content": null, 
        "query": "%22Apple%20$1.5%22", 
        "url": "http://twitter.com/search/?q=%22Apple%20$1.5%22"
      }, 
      {
        "events": null, 
        "name": "Zelko", 
        "promoted_content": null, 
        "query": "Zelko", 
        "url": "http://twitter.com/search/?q=Zelko"
      }, 
      {
        "events": null, 
        "name": "LWWY", 
        "promoted_content": null, 
        "query": "LWWY", 
        "url": "http://twitter.com/search/?q=LWWY"
      }, 
      {
        "events": null, 
        "name": "Lance Armstrong", 
        "promoted_content": null, 
        "query": "%22Lance%20Armstrong%22", 
        "url": "http://twitter.com/search/?q=%22Lance%20Armstrong%22"
      }, 
      {
        "events": null, 
        "name": "Gonzo", 
        "promoted_content": null, 
        "query": "Gonzo", 
        "url": "http://twitter.com/search/?q=Gonzo"
      }, 
      {
        "events": null, 
        "name": "Premium Rush", 
        "promoted_content": null, 
        "query": "%22Premium%20Rush%22", 
        "url": "http://twitter.com/search/?q=%22Premium%20Rush%22"
      }, 
      {
        "events": null, 
        "name": "Sweet Dreams", 
        "promoted_content": null, 
        "query": "%22Sweet%20Dreams%22", 
        "url": "http://twitter.com/search/?q=%22Sweet%20Dreams%22"
      }
    ]
  }
]
