=== juandesi/raml-to-retrofit/src/test/resources/twitter/schemas/trends-available-schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "country": {
        "required": false,
        "type": "string"
      },
      "countryCode": {
        "required": false,
        "type": "string"
      },
      "name": {
        "required": false,
        "type": "string"
      },
      "parentid": {
        "required": false,
        "type": "integer"
      },
      "placeType": {
        "required": false,
        "type": "object",
        "properties": {
          "code": {
            "required": false,
            "type": "integer"
          },
          "name": {
            "required": false,
            "type": "string"
          }
        }
      },
      "url": {
        "required": false,
        "type": "string"
      },
      "woeid": {
        "required": false,
        "type": "integer"
      }
    }
  }
}

=== juandesi/raml-to-retrofit/src/test/resources/twitter/examples/trends-available-example.json
[
  {
    "country": "Sweden", 
    "countryCode": "SE", 
    "name": "Sweden", 
    "parentid": 1, 
    "placeType": {
      "code": 12, 
      "name": "Country"
    }, 
    "url": "http://where.yahooapis.com/v1/place/23424954", 
    "woeid": 23424954
  }, 
  {
    "country": "United States", 
    "countryCode": "US", 
    "name": "New Haven", 
    "parentid": 23424977, 
    "placeType": {
      "code": 7, 
      "name": "Town"
    }, 
    "url": "http://where.yahooapis.com/v1/place/2458410", 
    "woeid": 2458410
  }, 
  {
    "country": "Japan", 
    "countryCode": "JP", 
    "name": "Sapporo", 
    "parentid": 23424856, 
    "placeType": {
      "code": 7, 
      "name": "Town"
    }, 
    "url": "http://where.yahooapis.com/v1/place/1118108", 
    "woeid": 1118108
  },
  {
    "country": "United States", 
    "countryCode": "US", 
    "name": "Providence", 
    "parentid": 23424977, 
    "placeType": {
      "code": 7, 
      "name": "Town"
    }, 
    "url": "http://where.yahooapis.com/v1/place/2477058", 
    "woeid": 2477058
  }, 
  {
    "country": "United States", 
    "countryCode": "US", 
    "name": "Cincinnati", 
    "parentid": 23424977, 
    "placeType": {
      "code": 7, 
      "name": "Town"
    }, 
    "url": "http://where.yahooapis.com/v1/place/2380358", 
    "woeid": 2380358
  }
]
